### ISSUE TITLE
Empty content attribute of meta tag not parsed correctly

### ISSUE THREAD

**Issue by testmigrator** [mylogin/htmlparser#3]
the result of doc->select("meta")->get_attr("content") is an empty string. Is this a bug?
```
TEST(test, findsCharsetInMalformedMeta){
    string h = "<meta http-equiv=Content-Type content=text/html; charset=gb2312>";
    parser parser;
    node_ptr doc = parser.parse(h);
    // ASSERT_EQ ("gb2312", doc->select("meta")->get_attr("content"));
}
```

**Comment by mylogin** [comment]
@testmigrator thanks for the tests!

`select` method can return multiple nodes, so they are grouped as children of the parent node. I've added the example code and fix.
